First impression with Chainer.

In [1]:
import chainer
import numpy as np

from chainer import *

import chainer.functions as F
import chainer.links as L
from chainer.training import extensions

Import the chainer essentials.

In [2]:
f = L.Linear(3,2) # dense MLP

x = Variable(np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)) # input
y = f(x) # process
y.data # output

array([[-0.43237969,  3.89886069],
       [-1.35355818,  8.12027836]], dtype=float32)

Per documentation:

>Gradients of parameters are computed by the backward() method. Note that gradients are accumulated by the method rather than overwritten. So first you must clear gradients to renew the computation. It can be done by calling the cleargrads() method.

In [5]:
f.cleargrads() # clear gradients of f

y.grad = np.ones((2, 2), dtype=np.float32) # provide ones as initial gradient
y.backward() # do backprop

# now the parameters have gradient
print(f.W.grad)
print(f.b.grad)

[[ 5.  7.  9.]
 [ 5.  7.  9.]]
[ 2.  2.]


In [11]:
f.W.data -= f.W.grad
f.b.data -= f.b.grad

y.data

array([[-0.43237969,  3.89886069],
       [-1.35355818,  8.12027836]], dtype=float32)