In [16]:
import tensorflow as tf

a = tf.Variable([[[1,2]],[[5,6]],[[7,8]]],dtype=tf.float32)
s = tf.shape(a)
z = tf.zeros(s)
stack = tf.stack([a,z],axis=1)
holed = tf.reshape(stack,[s[0],s[1]*2,s[2]])

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    res = sess.run([a,z,k,g])
    for i in res:
        print(i)
        if hasattr(i,'shape'):
            print('shape:',i.shape)
        print('----')

[[[ 1.  2.]]

 [[ 5.  6.]]

 [[ 7.  8.]]]
shape: (3, 1, 2)
----
[[[ 0.  0.]]

 [[ 0.  0.]]

 [[ 0.  0.]]]
shape: (3, 1, 2)
----
[[[[ 1.  2.]]

  [[ 0.  0.]]]


 [[[ 5.  6.]]

  [[ 0.  0.]]]


 [[[ 7.  8.]]

  [[ 0.  0.]]]]
shape: (3, 2, 1, 2)
----
[[[ 1.  2.]
  [ 0.  0.]]

 [[ 5.  6.]
  [ 0.  0.]]

 [[ 7.  8.]
  [ 0.  0.]]]
shape: (3, 2, 2)
----
